import type { Metadata, Viewport } from "next";
import "./globals.css"; 
import Providers from "@/provider/QuaryProvider";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "react-hot-toast";
import {Noto_Sans_Mono} from "next/font/google";

export const metadata: Metadata = {
  applicationName: "My Bank",
  manifest: "/manifest.json",
  title: "My Bank",
  description: "Generated by My Bank",
};
export const viewport: Viewport = {
  themeColor: "#181825",
};

const inter = Noto_Sans_Mono({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
         <Toaster position="top-right"reverseOrder={false} />
          <div className=" mt-[0px] ">
            {children}
          </div>
        </Providers>

      </body>
    </html>
  );
}
