import type { Metadata } from "next";
import "./globals.css"; 
import Providers from "@/provider/QuaryProvider";
import Navbar from "@/components/navbar";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "react-hot-toast";
import {Noto_Sans_Mono} from "next/font/google";
export const metadata: Metadata = {
  title: "My Bank",
  description: "Generated by My Bank",
};

const inter = Noto_Sans_Mono({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster />
          <div className=" mt-[0px] ">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
