import type { Metadata } from "next";
import "./globals.css"; 
import Providers from "@/quary/provider";
import Navbar from "@/components/navbar";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "My Bank",
  description: "Generated by My Bank",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Toaster />
          <Navbar />
          <div className=" mt-[75px] ">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
